name: Deploy Laravel to EC2
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
 
    - name: Deploy Laravel App to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.235.183.64 << 'EOF'
          # Clone fresh repo
          cd /tmp
          rm -rf fuodaybackend
          git clone https://github.com/Easwar-raj/fuodaybackend.git
          cd fuodaybackend

          # Inject .env securely
          echo '${{ secrets.LARAVEL_ENV }}' > .env
 
          # Move to web root
          sudo rm -rf /var/www/fuodaybackend
          sudo mv /tmp/fuodaybackend /var/www/fuodaybackend
          cd /var/www/fuodaybackend

          # Install dependencies
          composer install --no-interaction --prefer-dist --optimize-autoloader
 
          # Laravel setup
          php artisan key:generate
          php artisan storage:link
 
          # Fix permissions
          sudo chown -R www-data:www-data /var/www/fuodaybackend
          sudo chmod -R 775 storage bootstrap/cache
        EOF
